### ISSUE TITLE
Can't resolve 'fs' 

### ISSUE THREAD

**Issue by etiennepinchon** [defunctzombie/node-browser-resolve#102]
Hi,
I have having an issue with this package, as soon as I try to import it I am getting the following error:
```js
Failed to compile.

./node_modules/browser-resolve/index.js
Module not found: Can't resolve 'fs' in 'node_modules/browser-resolve'
```
Any idea what could cause this issue?

**Comment by ljharb** [comment]
Where is this error coming from?
