### ISSUE TITLE
purpose of empty.js

### ISSUE THREAD

**Issue by juliangruber** [defunctzombie/node-browser-resolve#32]
I see some 404 requests with the url `/Users/julian/pro/xxx/node_modules/browserify/node_modules/browser-resolve/empty.js`, what's that about?

**Comment by aft-luke** [comment]
This is a really old issue, but I'm not sure where else to ask for help. I'm getting this issue trying to run browserify (which uses browser-resolve) while running on a jenkins server:

```
AssertionError: no line 0 (line numbers start from 1) while
parsing file: /<path-to-proj>/node_modules/browser-resolve/empty.js
```

I have no idea where the problem is.

**Comment by shiitake** [comment]
@aft-luke I'm getting the exact same error so I've created a new issue for this. 

[AssertionError: no line 0 (line numbers start from 1) while parsing file node_modules\browser-resolve\empty.js](https://github.com/defunctzombie/node-browser-resolve/issues/79)
