### ISSUE TITLE
ability to specify alt browser mapping, for chromeapp or firefox app, etc.

### ISSUE THREAD

**Issue by mvayngrib** [defunctzombie/node-browser-resolve#55]
https://github.com/substack/node-browserify/issues/1094 

when I browserify for a Chrome app, I want a slightly different mapping than I specify in the "browser" field. It would be cool if I could have an arbitrarily named field and tell browserify to use that instead of "browser", e.g. 

    browserify --browser=chromeapp main.js > bundle.js

and 

    "browser": {
      ...
    },
    "chromeapp": {
      ...
    }

it would then default to "browser"

**Comment by defunctzombie** [comment]
What does @substack think about this? Are any other tools offering this functionality?

**Comment by substack** [comment]
This could be a useful feature and straightforward to implement.

**Comment by defunctzombie** [comment]
@mvayngrib want to take a stab at a PR please?

**Comment by mvayngrib** [comment]
sure, I'll take a stab
