### ISSUE TITLE
Use resolve 1.1.6

### ISSUE THREAD

**Issue by matthewp** [defunctzombie/node-browser-resolve#60]
1.1.6 has an important bug fix https://github.com/substack/node-resolve/pull/77 that is not in Browserify currently because browser-resolve is pinned to 1.1.5. Is there a reason why it is pinned this way?  If not can this be updated so that the fix makes its way to Browserify? @defunctzombie @substack

**Comment by defunctzombie** [comment]
Yes, it is pinned because I don't like code changing out from under me on every install.

Happy to review a PR that updates the dependency.

**Comment by matthewp** [comment]
Sure, no problem.
