### ISSUE TITLE
Resolve fails for requires without file extension

### ISSUE THREAD

**Issue by src-code** [defunctzombie/node-browser-resolve#69]
Ran into an issue recently running `module-deps`, which depends on `browser-resolve`, where a package which has a dependency with a `browser` field defined failed to resolve browser assets because the `require()` call omits the filename extension.

For example, package `asap` v2.0.3 defines the following `browser` field in `package.json`:

```json
"browser": {
    "./asap.js": "./browser-asap.js",
    "./raw.js": "./browser-raw.js",
    "./test/domain.js": "./test/browser-domain.js"
  },
```

And in a module such as `promise`, you'll find a `require()` such as:

```js
var asap = require('asap/raw')
```

This fails to resolve because `browser-resolve` doesn't seem to handle the missing extension when looking up the file in the `browser` field.  Adding the `.js` extension to the `require()` call fixes the issue.

Here's a simple test case calling `resolve()` directly:

```js 
var resolve = require('browser-resolve');

resolve('asap/raw', {}, function (err, path) {
    console.log('asap/raw -> ', path);
});

resolve('asap/raw.js', {}, function (err, path) {
    console.log('asap/raw.js -> ', path);
});
```

Output:

```js
asap/raw.js ->  /Users/steve/git/browser-resolve-bug/node_modules/asap/browser-raw.js
asap/raw ->  /Users/steve/git/browser-resolve-bug/node_modules/asap/raw.js
```

It'd be great if `browser-resolve` could resolve the missing extension automatically, otherwise tools like `module-deps` won't work with packages using shortened filenames.

**Comment by defunctzombie** [comment]
Great write up! Would you be willing to make a PR for this?

**Comment by src-code** [comment]
@defunctzombie Sure, I can take a stab at it... not sure how quickly though!
