### ISSUE TITLE
No support for npm module name with "scope" yet?

### ISSUE THREAD

**Issue by liujingbreak** [defunctzombie/node-browser-resolve#77]
Looks like it does not support it yet?
module name liks `@someScope/my-module`
https://docs.npmjs.com/misc/scope

**Comment by defunctzombie** [comment]
I have no tried it but would welcome a PR that adds support.

**Comment by liujingbreak** [comment]
hey @defunctzombie,
My bad, it actually works, I tried again it does support.
You can close this issue.

**Comment by liujingbreak** [comment]
Oh, my bad just again, tested again.
**New results**
It works in sync version `resolve.sync('@xx/yy') `
but failed to find a module with `scope` in async way `resolve('@xx/yy', callback)`

**Comment by liujingbreak** [comment]
Issue gone, I can not reproduce it again, probably it's my bad.
