### ISSUE TITLE
AssertionError: no line 0 (line numbers start from 1) while parsing file node_modules\browser-resolve\empty.js

### ISSUE THREAD

**Issue by shiitake** [defunctzombie/node-browser-resolve#79]
I'm actually getting this error when trying to run browserfy (via gulp) on my Windows 10 machine running node v 5.5.0.

**Comment by aft-luke** [comment]
I did a little digging, and here is another link: https://github.com/zertosh/unreachable-branch-transform/issues/14

**Comment by stephane-ruhlmann** [comment]
Same here with node v5.10.0 and v4.4.3.
+1 @aft-luke

**Comment by shiitake** [comment]
I was able to workaround this issue by adding a blank line (empty comment) into the empty.js file.

**Comment by stephane-ruhlmann** [comment]
@aft-luke problem seems to come from unreachable-branch-transform/recast

**Comment by aft-luke** [comment]
I agree @stephane-ruhlmann  that seems to be the root of the problem. For now I think I'm going to have to use `npm shrinkwrap` until the author @zertosh makes an appearance.

**Comment by zertosh** [comment]
Sorry everyone. I'll be on a computer in a few hours and push a fix to unreachable-branch-transform.

**Comment by defunctzombie** [comment]
Closing this as it appears to not be a problem in this module. If that is an incorrect assessment of the conversation please let me know.

**Comment by zertosh** [comment]
Published unreachable-branch-transform@0.5.1, which uses recast@^0.11.4.
